FROM registry.access.redhat.com/ubi10/go-toolset:10.0 AS builder

WORKDIR /opt/app-root/src

COPY go.mod go.sum* ./
RUN go mod download
## Copy the source code.
COPY main.go ./

RUN go build -o backend .

FROM registry.access.redhat.com/ubi10-minimal:10.0

WORKDIR /app

COPY --from=builder /opt/app-root/src/backend .

ENV DB_HOST=localhost \
    DB_PORT=5432 \
    DB_USER=guestbook \
    DB_PASSWORD=password \
    DB_NAME=guestbook \
    REDIS_HOST=localhost \
    REDIS_PORT=6379 \
    PORT=8080

EXPOSE 8080
CMD ["./backend"]